### ISSUE TITLE
Return YouTube Dislike 

### ISSUE THREAD

**Issue by ghost** [quoid/userscripts#378] opened 2022-11-16 11:21 UTC
![23D6A57C-6EDF-467F-8ED6-4AFB959BE6A9](https://user-images.githubusercontent.com/98572241/202166032-2ba7f69c-9f7a-4d13-a776-01bbed393310.png)
![58D5E6A4-DE59-4B1F-BCF5-4CA8DBC838F2](https://user-images.githubusercontent.com/98572241/202166040-44bf7323-0778-44ea-9653-29613c2e2e07.png)
![BA34EB8E-A246-4513-9D06-84F936F8A95B](https://user-images.githubusercontent.com/98572241/202166047-93165db6-31b7-490e-ac7f-f87491b0747e.png)

_System Information:_
> macOS or iOS version:15.7.1 IPhone 7 plus
> Userscripts version: 1.3.3
> Safari version:15.7.1
> Is this issue related to script injection?Im not sure
> Did the test script (pasted above) successfully run on your machine? I don’t know

**Comment by MalevolentRainbow** [comment] 2022-11-17 05:10
It doesn’t work it did nothing!

**Comment by MalevolentRainbow** [comment] 2022-11-17 07:19
Sorry I thought i did I’ll provide it now I got it off greasyfork 

https://greasyfork.org/scripts/436115-return-youtube-dislike/code/Return%20YouTube%20Dislike.user.js

https://greasyfork.org/en/scripts/436115-return-youtube-dislike


could you let me know what else detail information you need and I’ll be happy to provide it 😊 

I’m sorry by the way if I have not been very helpful for you to help 😅 iv actually never used GitHub issue respiratory before this is my first time

**Comment by MalevolentRainbow** [comment] 2022-11-17 08:35
Oh well is there a script that you can suggest this is related to the userscript app? I’m really just trying to figure out the app? And how to run it

**Comment by malicerainbow** [comment] 2022-11-17 11:49
But that’s just it ACTCD I don’t know if the issue is the script or the app! I don’t know how to test the test. And I assume maybe it’s just my phone because I am a iPhone 7 Plus. So could you please help me!!! I don’t know if it’s an issue with the extension or issue with the app. I have not been able to perform the test the test you offer so please help me so I can know if it’s the extension or if it’s the script

**Comment by malicerainbow** [comment] 2022-11-17 20:29
But can you tell me how to run the test so I can see if it will work on my phone? I have an iPhone 7 Plus and I need to make sure my phone is not the issue for me. But I won’t know unless I do the test so can you please show me how to perform the test please? So I can be on my way?

**Comment by malicerainbow** [comment] 2022-11-17 20:44
Can you please delete the duplicates?

**Comment by malicerainbow** [comment] 2022-11-17 20:50
If you will just help me ACTCD on how to do the testscript my self so I can know it’s not my phone it’s not my software it’s not anything to do on my side

because I need to know if I need to buy a new iPhone or not!

So will you please help me!

**Comment by malicerainbow** [comment] 2022-11-17 23:01
![E24E9D3A-8AF5-4DF6-9B0D-B1B72EB4E2FB](https://user-images.githubusercontent.com/118444664/202578182-1ab87ab8-978a-4590-a6d1-2467ba7fdcf5.png)


It keeps saying failed to get init data



I didn’t know that after a closed issue you could still comment

plus I wasn’t sure if you would see my comments still

**Comment by malicerainbow** [comment] 2022-11-17 23:10
Just so I’m clear this is how you install it correct? You click on the link you sent me where it takes you to a new page with the script you click the aA puzzle icon select userscript and than userscript runs the script? 
![E10F1312-DFF8-446C-A7B8-50AD1CA31E2C](https://user-images.githubusercontent.com/118444664/202579051-4cbc76b0-f9e2-49ae-842c-4c0b4e2c6229.jpeg)
![AA729FAE-7EDA-4323-9FF6-40C3918563F5](https://user-images.githubusercontent.com/118444664/202579057-53138918-ece1-4dc6-9d1f-8221577d67c4.jpeg)
![F259958A-E01D-4F76-8915-9AD65F75FE69](https://user-images.githubusercontent.com/118444664/202579059-2a857694-4d25-4db5-b9bb-b7f4668cf418.png)
![94200C01-7773-4700-B0CC-DDF893F850DC](https://user-images.githubusercontent.com/118444664/202579061-931d2d2c-5e98-4b20-8911-aed137217da9.png)


Also if I select userscript the app just keeps buffering with the loading spiral I have to click my home button and than swipe out of the safari tab on my phone than go back into safari repeat the process and finally it finishes loading but I get this 


Failed to get init data

**Comment by malicerainbow** [comment] 2022-11-17 23:14
I was desperate and worried once an issue is closed no more commenting or no more notifying the helper in this case you


I have never used GitHub issue before so I don’t know if when an issue is close you can still comment and when you just closed the other ones I assumed you weren’t reading what I need help with 

but now that I know you are willing to still continue communication on this one I won’t make anymore duplicates I’m just desperate and worried here

**Comment by malicerainbow** [comment] 2022-11-17 23:18
I have uninstalled reinstalled the app multiple times tried your script again of clicking the link going to aA puzzle icon near the url link bar on my safari phone screen selected userscripts and it still gives me 


Failed to get init data

**Comment by malicerainbow** [comment] 2022-11-18 00:32
Every attempt that happens, we’ll see that’s the weirdest part in order for me to install the script I have to actually save the exact script as a file and than set userscripts directory to exactly that file location so if the script is in “On my IPhone” in exactly “Downloads” I have to set the userscript directory to there 
![93A23D45-677E-4136-A200-29F077D624EB](https://user-images.githubusercontent.com/118444664/202589023-d713b084-b41a-464b-bfe6-8508ecf02974.png)
![8C29182C-5FE4-4EF4-AE88-FE61C6125A4D](https://user-images.githubusercontent.com/118444664/202589028-aaba1508-f527-4d7c-8947-b22f38fcd048.png)



once the script is already on my phone in my files than I can go to a link of a script go to aA puzzle icon select userscript and than I see finally the script and it ask if I wish to download but even than it doesn’t do anything 

and I only not get “failed to get init data” if the script is already saved to my iPhones file app if it’s not saved than I get the error message 

is there a discord or something I can message you on? So that maybe this could be more resolved with sharing my screen?

**Comment by quoid** [comment] 2022-11-18 00:39
@malicerainbow 

> Just so I’m clear this is how you install it correct? You click on the link you sent me where it takes you to a new page with the script you click the aA puzzle icon select userscript and than userscript runs the script?

No that is not how it works. I have outlined the steps below:

1) Install App from [App Store](https://itunes.apple.com/us/app/userscripts/id1463298887)

2) Open App (not extension)

3) Click `Set Userscripts Directory` - this is where the app will **read** from, where you user scripts will be located - this should be a **folder** and probably an **iCloud** folder so it can sync between your desktop and phone

4) Install some user scripts - typically this is done on a desktop machine - put user scripts file in the directory you set in step 3

4a) Alternatively you can **install** userscripts by visiting a page that has, like @ACTCD linked before - https://raw.githubusercontent.com/ACTCD/Userscripts/dev/debug/DEBUG.Alert-URL.user.js

4b) When on that page, open the **extension popup** from clicking on the puzzle icon in the address bar

4c) After the popup opens, you should see a yellow bar that says `Tap to Install`, tap that and proceed to install

4d.) At this point the user script should be installed and *depending on the metadata* should run when you navigate to a page that is matched - in the case of the user script linked above, it should run on every web page

5) Now that the user script is installed, dismiss the popup and visit any other page (like https://www.example.com/) and re-open the popup, you should now see the script you just installed (linked above) show up in in the popup

6) When visiting https://www.example.com/ you should have seen an alert

**Comment by quoid** [comment] 2022-11-18 00:46
@malicerainbow 

> is there a discord or something I can message you on?

We have a Matrix server, but I am unsure if it is public at the moment or if you use Matrix.

Concerning your screenshot above, if the **application** does not have a directory selected you will get errors. You must set a directory from which you will save and read user scripts from. 

I see in the 2nd screenshot it says `Select a directory to load userscripts`, but the first one has a proper directory. Make sure you have a valid directory set before trying to use the extension.

>  the weirdest part in order for me to install the script I have to actually save the exact script as a file and than set userscripts directory to exactly that file location 

You want to set the direct *before* saving any files, typically.

> if the script is in “On my IPhone” in exactly “Downloads” 

Yes, the folder that holds your user scripts is what you should set in the application. This where the extension reads the data (userscripts) to inject into webpages. Can you elaborate on why this sounds weird to you?

**Comment by malicerainbow** [comment] 2022-11-18 00:48
Okay I think it installed but how do I know it worked?
![FA9C2902-7C4A-4FD5-9663-C81FEA102D52](https://user-images.githubusercontent.com/118444664/202590821-d5daffdd-6781-41f6-9582-e14b0e05e701.png)
![631DD980-E0CB-4B11-B7E4-555B52C49136](https://user-images.githubusercontent.com/118444664/202590850-9cdc2f42-e4e4-40e2-ae16-e23e31eebc08.png)


I set the userscripts directory to My iPhone folder scripts I did get the option to install this time but how do I know it worked?

**Comment by malicerainbow** [comment] 2022-11-18 00:50
Wait I think it worked this message means it worked correct? 
![E56DBFEB-67CE-4026-8BAF-747D41CA7C37](https://user-images.githubusercontent.com/118444664/202591134-6e7bee54-003e-45c3-b21a-33905d8f107b.png)
![A1F90E85-F5EF-4E09-A9AC-1CBA72C9E404](https://user-images.githubusercontent.com/118444664/202591137-59135538-705c-4479-bf70-93c1acb59478.png)

**Comment by quoid** [comment] 2022-11-18 00:51
@malicerainbow 

That means it is working.

**Closed** 2022-11-18 00:51 UTC
Labels: question, unrelated

**Comment by quoid** [comment] 2022-11-18 00:52
@malicerainbow 

I closed this issue. If have more questions, please ask them here: https://github.com/quoid/userscripts/discussions/categories/general - this is the place for more general usage questions.

If you encounter a reproducible bug, feel free to make a new issue.

**Comment by malicerainbow** [comment] 2022-11-18 01:08
So if a particular script does not work? Than now we know it’s not the app or my phone it’s that particular script 

correct?

**Comment by malicerainbow** [comment] 2022-11-18 01:13
So wait no matter what script it is all I have to do is make sure my Userscripts app on and the directory is set to a location and than go to the script have the code on your screen click aA puzzle icon select Userscripts tap install, and than go to what ever that script is for go into aA puzzle icon again select Userscripts again let it load and click the script that installed to make sure it’s lit and that’s it? 


after that if script still does not work I did nothing wrong? The app is fine and my phone is fine right?

**Comment by quoid** [comment] 2022-11-18 01:34
> Than now we know it’s not the app or my phone it’s that particular script

Sometimes it is not that easy. There could be issues with the app/extension that are only exposed by certain userscripts. But by running the test script we know that *basic script injection* is working and it helps us narrow down the issues.

> So wait no matter what script it is all I have to do is make sure my Userscripts app on and the directory is set to a location and than go to the script have the code on your screen click aA puzzle icon select Userscripts tap install, and than go to what ever that script is for go into aA puzzle icon again select Userscripts again let it load and click the script that installed to make sure it’s lit and that’s it?

Yes, for the most part that's how it works. You go to a script file online, `Tap to Install`, and go to the website where it is supposed to work and depending on the script, it should work.

> after that if script still does not work I did nothing wrong? The app is fine and my phone is fine right?

If the script doesn't work after that, open the popup and make sure it is showing for that website. The popup (what you access from the puzzle icon) only shows scripts in there when they match a website. For example, is you install a script called `myScript01.user.js` and it is supposed to run **only** on `google.com` and you visit `google.com` on your phone and the open the popup, you should see `myScript01.user.js`, but if you went to `twitter.com` and then opened the popup, you should **not** see `myScript01.user.js` in the popup.

If you visit a site where the script should run and it is does not, open the popup and make sure it shown and reload the site. If it doesnt run after that, it is often a problem with the script, but could be with the app/extension.

Remember, people write these scripts for many different browsers and Safari is usually not top priority. Firefox, Chrome and Safari all have different features so something that works in Chrome will not always work in Safari.

**Comment by malicerainbow** [comment] 2022-11-18 03:10
So now how do we figure out if this not script is not functional or it is functional and the app or my phone is the issue? 

This is the script by the way if you want to test it it’s the Return YouTube Dislike script 

https://raw.githubusercontent.com/Anarios/return-youtube-dislike/main/Extensions/UserScript/Return%20Youtube%20Dislike.user.js


And here is the website it comes from 

https://www.returnyoutubedislike.com/


I can’t get it to work and I’m assuming since debug worked it’s not my phone or the app but than you said most of the time 

so could we please find out if the script is the problem after all or not?

**Comment by malicerainbow** [comment] 2022-11-18 03:11
![C6286584-1707-4E05-B7ED-46C50BFE3148](https://user-images.githubusercontent.com/118444664/202608218-fb4fc63c-3bce-425e-a7aa-a0b1c2ffd7e7.png)
![550B5AA2-F3B5-440C-A1CF-71D9821144F0](https://user-images.githubusercontent.com/118444664/202608223-bb80f8e8-cb7e-4947-ab3a-aabd12e622ad.png)
![132226B7-880E-452D-81C1-E04137010A1C](https://user-images.githubusercontent.com/118444664/202608225-c1b7c420-37a2-41c0-9942-16cd41edaa14.png)
![09C65D9B-84C6-4BCC-A386-8D02F0FC0511](https://user-images.githubusercontent.com/118444664/202608227-75c59fe3-4afc-4478-8f62-9f0b715b848c.png)
![F12F914D-4A24-4F4A-ACB7-7AAB7218021E](https://user-images.githubusercontent.com/118444664/202608228-312d7120-6b00-4304-9d30-79071a35fd69.png)
![44026869-0955-4F04-AB72-65CE051196EE](https://user-images.githubusercontent.com/118444664/202608229-bf49aa12-6d0d-4f1b-8585-c4042c92e8a2.jpeg)
![627CA3F6-24CE-4468-81CD-5679083AA747](https://user-images.githubusercontent.com/118444664/202608230-10ee105e-9c38-4a82-b6b3-487c8fc9c33b.jpeg)
![69F853C1-1562-4E42-A745-A852097F4A37](https://user-images.githubusercontent.com/118444664/202608232-f478f066-2c13-4abb-8657-17d44bd7fec1.jpeg)
![3FF54D47-0F28-4D53-A46B-B3E670E4D4E0](https://user-images.githubusercontent.com/118444664/202608234-eb7fb2fe-88ad-4a10-95ba-31a2120a17bf.png)
![263C5605-5CF2-4070-AE15-FAD8B03CE5FC](https://user-images.githubusercontent.com/118444664/202608235-f0390cd5-35fb-413e-8910-4c6c61df2480.png)
![D6DCFA6C-5C04-4BF9-B714-CC26370CC604](https://user-images.githubusercontent.com/118444664/202608236-2cced9f5-d119-4525-83e2-ee775432b852.jpeg)
![31067BD8-ADE6-4311-BB59-4360B5031854](https://user-images.githubusercontent.com/118444664/202608238-0cddb908-9432-47e9-b2de-a25bd423d774.jpeg)




I don’t know if the issue is the app or the issue is the script?

**Comment by malicerainbow** [comment] 2022-11-18 03:17
> > Than now we know it’s not the app or my phone it’s that particular script
> 
> Sometimes it is not that easy. There could be issues with the app/extension that are only exposed by certain userscripts. But by running the test script we know that _basic script injection_ is working and it helps us narrow down the issues.
> 
> > So wait no matter what script it is all I have to do is make sure my Userscripts app on and the directory is set to a location and than go to the script have the code on your screen click aA puzzle icon select Userscripts tap install, and than go to what ever that script is for go into aA puzzle icon again select Userscripts again let it load and click the script that installed to make sure it’s lit and that’s it?
> 
> Yes, for the most part that's how it works. You go to a script file online, `Tap to Install`, and go to the website where it is supposed to work and depending on the script, it should work.
> 
> > after that if script still does not work I did nothing wrong? The app is fine and my phone is fine right?
> 
> If the script doesn't work after that, open the popup and make sure it is showing for that website. The popup (what you access from the puzzle icon) only shows scripts in there when they match a website. For example, is you install a script called `myScript01.user.js` and it is supposed to run **only** on `google.com` and you visit `google.com` on your phone and the open the popup, you should see `myScript01.user.js`, but if you went to `twitter.com` and then opened the popup, you should **not** see `myScript01.user.js` in the popup.
> 
> If you visit a site where the script should run and it is does not, open the popup and make sure it shown and reload the site. If it doesnt run after that, it is often a problem with the script, but could be with the app/extension.
> 
> Remember, people write these scripts for many different browsers and Safari is usually not top priority. Firefox, Chrome and Safari all have different features so something that works in Chrome will not always work in Safari.



> > Than now we know it’s not the app or my phone it’s that particular script
> 
> Sometimes it is not that easy. There could be issues with the app/extension that are only exposed by certain userscripts. But by running the test script we know that _basic script injection_ is working and it helps us narrow down the issues.
> 
> > So wait no matter what script it is all I have to do is make sure my Userscripts app on and the directory is set to a location and than go to the script have the code on your screen click aA puzzle icon select Userscripts tap install, and than go to what ever that script is for go into aA puzzle icon again select Userscripts again let it load and click the script that installed to make sure it’s lit and that’s it?
> 
> Yes, for the most part that's how it works. You go to a script file online, `Tap to Install`, and go to the website where it is supposed to work and depending on the script, it should work.
> 
> > after that if script still does not work I did nothing wrong? The app is fine and my phone is fine right?
> 
> If the script doesn't work after that, open the popup and make sure it is showing for that website. The popup (what you access from the puzzle icon) only shows scripts in there when they match a website. For example, is you install a script called `myScript01.user.js` and it is supposed to run **only** on `google.com` and you visit `google.com` on your phone and the open the popup, you should see `myScript01.user.js`, but if you went to `twitter.com` and then opened the popup, you should **not** see `myScript01.user.js` in the popup.
> 
> If you visit a site where the script should run and it is does not, open the popup and make sure it shown and reload the site. If it doesnt run after that, it is often a problem with the script, but could be with the app/extension.
> 
> Remember, people write these scripts for many different browsers and Safari is usually not top priority. Firefox, Chrome and Safari all have different features so something that works in Chrome will not always work in Safari.



okay so now you got me worried that issue could be the app or my phone 

my phone is old it’s a iPhone 7 Plus I don’t even know if it ran the software accordingly but if it did it’s 15.7.1 

and the app version I have is 1.3.3 


I’m trying to figure out if I need a newer iPhone or is the issue not my phone or the app? That’s what I’m trying to figure out

**Comment by quoid** [comment] 2022-11-18 03:26
@malicerainbow 

The issue is with that user script (Return Youtube Dislike), it's not the app/extension in this case. You should reach out the author and ask them to update it.

**Comment by malicerainbow** [comment] 2022-11-18 03:44
Great! But can you please show me how it’s been confirmed it’s not the app or my phone? 

1 I’m interested in this stuff
2 I need to know that you did what I did and it didn’t work or did you do something else and it didn’t work? Because, maybe I’m still not doing something right! Granted you yourself tested it so now we know it doesn’t work. But what if I’m still not doing it right. So when there’s a script that is working functionally I may not even know because I didn’t do the correct steps that you did. But if you did do exactly what I did than I did do it correctly only I don’t know yet because I don’t know what exactly you did to run the script?

**Comment by malicerainbow** [comment] 2022-11-18 03:44
Also where is the link for the discord server?

**Comment by quoid** [comment] 2022-11-18 03:49
> Great! But can you please show me how it’s been confirmed it’s not the app or my phone?

I installed the userscript, I see it gets injected and see that it is not doing what it is supposed to. I can see this because I am using it on desktop and looking at the browser console.

The problem seems to be with the way the author is trying to create the new DOM elements. (screen shot below showing that it does properly get the dislike score).

I am not going to debug it further because I didn't write the code and it is not my user script.

> Also where is the link for the discord server?

No discord server, but there is a Matrix server. It's pretty quiet there. I will talk to @ACTCD about getting the link.
<img width="1088" alt="Screen Shot 2022-11-17 at 10 47 38 PM" src="https://user-images.githubusercontent.com/7660254/202612677-2f625a96-c974-4461-9e59-d03a04684600.png">

**Comment by malicerainbow** [comment] 2022-11-18 03:55
It worked!!!!! You were right it just needed an update it worked!!!! Oh my universe I could hug you!!!!! 


thank you!!!!!!!

**Comment by malicerainbow** [comment] 2022-11-18 04:06
Okay so now I have an issue I think the script I guess worked if the updated but every single video and I mean I did even YouTube’s number one popular video there all saying 12k dislikes 

I just can’t see how every single video is 12 thousand dislikes that just doesn’t make an probable sense 


Here is the updated is this an issue with the app or still with the script?


https://raw.githubusercontent.com/hyperstown/return-youtube-dislike/main/Extensions/UserScript/Return%20Youtube%20Dislike.user.js

**Comment by malicerainbow** [comment] 2022-11-18 04:20
Never mind! I figured it out you have to refresh for each different video a little weird and tedious but whatever

**Comment by malicerainbow** [comment] 2022-11-18 07:09
Wait what’s matrix?

**Comment by malicerainbow** [comment] 2022-11-19 05:38
Okay that’s fine but if I can get to t hi s matrix thing how will you guys give me the link if not here?

**Comment by quoid** [comment] 2022-11-19 14:06
@malicerainbow 

When we have a room set up I will post it the discussions area: https://github.com/quoid/userscripts/discussions

we do not currently have any public rooms set up, so for now, use the discussions area: https://github.com/quoid/userscripts/discussions
