### ISSUE TITLE
Userscripts extension stops working after a while of Safari uptime until Safari is quit and restarted

### ISSUE THREAD

**Issue by v7rzlhb3xg** [quoid/userscripts#245] opened 2022-04-30 18:17 UTC
Hey, I think I noticed this begin to happen with the latest macOS update. After a while of having Safari open I'll notice that Userscripts just stops working -- no scripts are being injected and the developer console doesn't show any Userscripts activity either. Clicking on the Userscripts extension icon in my Safari toolbar also just gives me the endless spinning loading circle. The only thing that seems to fix it is restarting Safari again. I've experienced this on both the App Store release version as well as the latest TestFlight beta version. Let me know if there's any more information I can provide.

_System Information:_
> macOS or iOS version: macOS Monterey 12.3.1
> Userscripts version: 4/1/7 (47)
> Safari version: 15.4
> Is this issue related to script injection? Yes

**Comment by quoid** [comment] 2022-05-01 00:19
@v7rzlhb3xg 

Thanks for reporting this. I have some follow up questions/comments:

>  noticed this begin to happen with the latest macOS update

Are you referring to the macOS 12.3.1 update? or an update to the userscripts app?

> and the developer console doesn't show any Userscripts activity either

Another place that you can look, if you don't mind, is the browser tools for the extension itself. There are two areas you can do this.

### Extension popup
If you right click anywhere in the extension popup, you should get a tooltip that offer the option called `Inspect Element`. When you select that option a browser tools will open and if you navigate the `Console` section you will see error that are specific to the extension popup. 

Extension popup errors do not get logged in the "normal" browser console.
<img width="703" alt="Screen Shot 2022-04-30 at 8 05 31 PM" src="https://user-images.githubusercontent.com/7660254/166126702-49a5adfb-73f5-49af-80f6-a35d7d7f44e0.png">

## Background page
The background page is where a lot of the app logic lives. When errors occur here, they also do not log in the "normal" browser console, but you can view the browser tools for this background page by navigating to the Safari option `Developer > Web Extension Background Pages > Userscripts`.

You might notice that the background page for this app might be labeled as `Userscripts (not loaded)` or `Userscripts - Background Page`. This is because this extension uses a [non-persistent background page](https://developer.apple.com/documentation/safariservices/safari_web_extensions/optimizing_your_web_extension_for_safari), or "event-driven" background page. When the background page has responded to an event in a while, it unloads itself. This is **required** for iOS and likely will soon be required for macOS. For consistency and code-sharing I use  the same background page in both macOS and iOS.

That being said, when you click on the option for `Userscripts` in that menu, a browser tools should open and you can navigate to the `Console` section and see any errors that have been logged.

<img width="1065" alt="Screen Shot 2022-04-30 at 8 11 53 PM" src="https://user-images.githubusercontent.com/7660254/166126805-0ce84224-d5d4-4021-b04d-4d8e43792632.png">

### Console.app

The last place to check for errors is `Console.app`. There's [some directions on how to do that here](https://github.com/quoid/userscripts/issues/201#issuecomment-1009499586). However, I believe you would likely see errors using the above 2 methods if you are seeing a spinning loading element but nothing happening in popup.

---

If I had to guess, I would say that the extension (for some reason) stopped responding to events, which drives the logic throughout the different parts of the app. As mentioned above, this extension is event-driven and the background and popup page simply listen for various events and respond accordingly.

At one point I did encounter an issue while working locally where the extension stopped responding to events, for no discernible reason. From what I saw, it simply stopped responding to events. Unfortunately I could not reproduce the issue and it spontaneously stopped presenting itself; I can not recall if that was before or after the most recent macOS update.

My gut tells me this could be an upstream issue with Safari, since the event logic is fairly standard. 

If you encounter this again and are up to doing some bug checking using the methods above I would really appreciate it. Also, if you figure out a way to reliably reproduce the issue please let me know.

**Comment by v7rzlhb3xg** [comment] 2022-05-01 17:03
@quoid 

> Are you referring to the macOS 12.3.1 update? or an update to the userscripts app?

Sorry, that wasn't clear -- I'm referring to the latest macOS 12.3.1 update, that seems to coincide with when I started noticing this issue with Userscripts.

Unfortunately, nothing seems to be coming up in the developer console in either of the first two methods you listed. Opening the Console.app and filtering for any Userscripts related logs does have some results though, here are some screenshots of that. Not entirely sure what's normal and what isn't so I've included everything I could find! Can't seem to figure out a way to reproduce it reliably other than just having Safari open for half a day or so. I'll mess around with the scripts I have installed to see if it's a certain one potentially acting up.

<img width="1169" alt="Screen Shot 2022-05-01 at 1 00 09 PM" src="https://user-images.githubusercontent.com/18043024/166156300-faf654c1-40ca-424a-ba57-d84e97ff20a9.png">
<img width="1169" alt="Screen Shot 2022-05-01 at 12 59 49 PM" src="https://user-images.githubusercontent.com/18043024/166156302-ae7e5329-b473-492d-8515-8ff7757f9b93.png">
<img width="1169" alt="Screen Shot 2022-05-01 at 12 59 52 PM" src="https://user-images.githubusercontent.com/18043024/166156303-c1b41a78-99ad-4742-b9c4-66a0a49392f2.png">
<img width="1169" alt="Screen Shot 2022-05-01 at 12 59 55 PM" src="https://user-images.githubusercontent.com/18043024/166156304-7cfecb6b-124d-42e0-b231-eec4b73a3207.png">

**Comment by quoid** [comment] 2022-05-01 17:48
@v7rzlhb3xg thank you for looking into this

> Unfortunately, nothing seems to be coming up in the developer console in either of the first two methods you listed. 

I am surprised nothing was logged there. That makes me think what you are experiencing is different than what I experienced and that my theory as to what was going in is incorrect.

>  Opening the Console.app and filtering for any Userscripts related logs does have some results though

Most of those are spurious "errors". They've existed since the inception of the extension and Apple has said they can safely be ignored. However that first error, about the CPU usage, I have never seen before. When looking at my own console, I do see similar message for other apps (image below). 

I'm not sure if that's indicating an issue, but seeing that 100% cpu is being used by the extension for that long doesn't feel right, even if it is not the cause of the issue at hand.

> Can't seem to figure out a way to reproduce it reliably other than just having Safari open for half a day or so.

When you have Safari open, does your macbook remain open as well or are you closing the lid/sleeping the machine and just continuing your session?

For me, I tend to keep quite long safari sessions, but I do sleep the my macbook when not being used (by closing the lid). I am curious if there's a way I could try to repro the bug on my machine as well.

Also, if you don't mind, could you share what hardware macbook version youre using?

**Comment by zexpe** [comment] 2022-05-21 17:10
I have the same problem where I open my MacBook Pro (M1 Pro 2021) and notice that the Userscripts extension is using 100% CPU, as if it were stuck in an infinite loop. Disabling and re-enabling the extension gets it working fine again, but it regularly returns to this state after the laptop is closed and opened again. I also first noticed this about a month ago, so it may be macOS 12.3.1 related.

**Comment by v7rzlhb3xg** [comment] 2022-05-21 17:13
The issue I was having has seemingly resolved itself between upgrading to macOS Monterey 12.4, doing a full clean and fresh reinstall of Userscripts from the App Store, and then reinstalling the beta version. Not sure what exactly fixed it!

**Comment by quoid** [comment] 2022-05-21 17:40
@zexpe 

> ...and notice that the Userscripts extension is using 100% CPU...


Is it possible for you to provide a screenshot of the console and any diagnostic or bug reports from `console.app` that mention Userscripts?

I am not sure what this could be, whether or not there is an issue with our code or something with macos or safari.

**Comment by zexpe** [comment] 2022-05-21 18:57
Ah, I was going to check if 12.4 was out, but I forgot... I will install that and see if the issue goes away.

@quoid here's a paste of the console log:

> Date/Time:        2022-05-21 15:46:14.669 +0100
> End time:         2022-05-21 15:48:38.991 +0100
> OS Version:       macOS 12.3.1 (Build 21E258)
> Architecture:     arm64e
> Report Version:   35
> Incident Identifier: 95E8A289-7565-4E55-AE27-20218F3FE617
> Share With Devs:  Yes
> 
> Data Source:      Microstackshots
> Shared Cache:     1DF3DFC1-141A-35D0-A4E5-F1E113894C6E slid base address 0x1a88a8000, slide 0x288a8000
> 
> Command:          Userscripts Extension
> Path:             /Applications/Userscripts.app/Contents/PlugIns/Userscripts Extension.appex/Contents/MacOS/Userscripts Extension
> Identifier:       com.userscripts.macos.Userscripts-Extension
> Version:          4.1.0 (47)
> Team ID:          J74Q8V8V8N
> Architecture:     arm64
> Parent:           UNKNOWN [1]
> PID:              43516
> 
> Event:            cpu usage
> Action taken:     none
> CPU:              144 seconds cpu time over 144 seconds (100% cpu average), exceeding limit of 80% cpu over 180 seconds
> CPU limit:        144s
> Limit duration:   180s
> CPU used:         144s
> CPU duration:     144s
> Duration:         144.32s
> Duration Sampled: 143.30s
> Steps:            73
> 
> Hardware model:   MacBookPro18,1
> Active cpus:      10
> HW page size:     16384
> VM page size:     16384
> 
> Fan speed:        0 rpm
> Advisory levels:  Battery -> 3, User -> 2, ThermalPressure -> 0, Combined -> 2
> Free disk space:  367.43 GB/460.43 GB, low space threshold 3072 MB
> 
> Heaviest stack for the target process:
>   73  start + 516 (dyld + 20616) [0x100dcd088]
>   73  NSExtensionMain + 240 (Foundation + 1010000) [0x1a9c0b950]
>   73  EXExtensionMain + 300 (ExtensionFoundation + 134848) [0x1bb6d8ec0]
>   73  ??? (PlugInKit + 120532) [0x1b42976d4]
>   73  ??? (PlugInKit + 118512) [0x1b4296ef0]
>   73  ??? (PlugInKit + 119500) [0x1b42972cc]
>   73  -[NSXPCListener resume] + 344 (Foundation + 549388) [0x1a9b9b20c]
>   73  xpc_main + 108 (libxpc.dylib + 98768) [0x1a89131d0]
>   73  _xpc_objc_main + 876 (libxpc.dylib + 100532) [0x1a89138b4]
>   73  -[NSRunLoop(NSRunLoop) run] + 92 (Foundation + 1000964) [0x1a9c09604]
>   73  -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236 (Foundation + 410128) [0x1a9b79210]
>   73  CFRunLoopRunSpecific + 600 (CoreFoundation + 533648) [0x1a8c9c490]
>   73  __CFRunLoopRun + 2532 (CoreFoundation + 538132) [0x1a8c9d614]
>   73  __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16 (CoreFoundation + 812004) [0x1a8ce03e4]
>   73  _dispatch_main_queue_callback_4CF + 44 (libdispatch.dylib + 74524) [0x1a8a1c31c]
>   73  _dispatch_main_queue_drain + 928 (libdispatch.dylib + 75468) [0x1a8a1c6cc]
>   73  _dispatch_client_callout + 20 (libdispatch.dylib + 16840) [0x1a8a0e1c8]
>   73  _dispatch_call_block_and_release + 32 (libdispatch.dylib + 9732) [0x1a8a0c604]
>   73  __112-[EXConcreteExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]_block_invoke + 1092 (ExtensionFoundation + 140920) [0x1bb6da678]
>   73  -[EXExtensionContextImplementation _willPerformHostCallback:] + 84 (ExtensionFoundation + 73372) [0x1bb6c9e9c]
>   73  __112-[EXConcreteExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]_block_invoke.199 + 228 (ExtensionFoundation + 141888) [0x1bb6daa40]
>   73  ??? (Userscripts Extension + 20736) [0x100c45100]
>   73  ??? (Userscripts Extension + 26896) [0x100c46910]
>   73  ??? (Userscripts Extension + 46292) [0x100c4b4d4]
>   73  ??? (Userscripts Extension + 146412) [0x100c63bec]
>   73  ??? (Userscripts Extension + 142224) [0x100c62b90]
>   73  -[NSRegularExpression(NSMatching) firstMatchInString:options:range:] + 188 (Foundation + 775596) [0x1a9bd25ac]
>   73  -[NSRegularExpression(NSMatching) enumerateMatchesInString:options:range:usingBlock:] + 620 (Foundation + 388468) [0x1a9b73d74]
>   73  icu::RegexMatcher::find(UErrorCode&) + 1664 (libicucore.A.dylib + 1915168) [0x1ab21d920]
>   10  icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 9696 (libicucore.A.dylib + 1927628) [0x1ab2209cc]
> 
> 
> Powerstats for:   Userscripts Extension [43516] [unique pid 541066]
> UUID:             9CB60DBB-6C48-378F-B79B-FEB4D68D79E5
> Path:             /Applications/Userscripts.app/Contents/PlugIns/Userscripts Extension.appex/Contents/MacOS/Userscripts Extension
> Identifier:       com.userscripts.macos.Userscripts-Extension
> Version:          4.1.0 (47)
> Team ID:          J74Q8V8V8N
> Architecture:     arm64
> Parent:           UNKNOWN [1]
> UID:              501
> Sudden Term:      Tracked (allows idle exit)
> Footprint:        5440 KB -> 5856 KB (+416 KB)
> Start time:       2022-05-21 15:46:15.363 +0100
> End time:         2022-05-21 15:48:38.666 +0100
> Num samples:      73 (100%)
> Primary state:    73 samples Non-Frontmost App, Non-Suppressed, User mode, Effective Thread QoS Default, Requested Thread QoS Default, Override Thread QoS Unspecified
> User Activity:    0 samples Idle, 73 samples Active
> Power Source:     3 samples on Battery, 70 samples on AC
>   73  start + 516 (dyld + 20616) [0x100dcd088]
>     73  NSExtensionMain + 240 (Foundation + 1010000) [0x1a9c0b950]
>       73  EXExtensionMain + 300 (ExtensionFoundation + 134848) [0x1bb6d8ec0]
>         73  ??? (PlugInKit + 120532) [0x1b42976d4]
>           73  ??? (PlugInKit + 118512) [0x1b4296ef0]
>             73  ??? (PlugInKit + 119500) [0x1b42972cc]
>               73  -[NSXPCListener resume] + 344 (Foundation + 549388) [0x1a9b9b20c]
>                 73  xpc_main + 108 (libxpc.dylib + 98768) [0x1a89131d0]
>                   73  _xpc_objc_main + 876 (libxpc.dylib + 100532) [0x1a89138b4]
>                     73  -[NSRunLoop(NSRunLoop) run] + 92 (Foundation + 1000964) [0x1a9c09604]
>                       73  -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236 (Foundation + 410128) [0x1a9b79210]
>                         73  CFRunLoopRunSpecific + 600 (CoreFoundation + 533648) [0x1a8c9c490]
>                           73  __CFRunLoopRun + 2532 (CoreFoundation + 538132) [0x1a8c9d614]
>                             73  __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16 (CoreFoundation + 812004) [0x1a8ce03e4]
>                               73  _dispatch_main_queue_callback_4CF + 44 (libdispatch.dylib + 74524) [0x1a8a1c31c]
>                                 73  _dispatch_main_queue_drain + 928 (libdispatch.dylib + 75468) [0x1a8a1c6cc]
>                                   73  _dispatch_client_callout + 20 (libdispatch.dylib + 16840) [0x1a8a0e1c8]
>                                     73  _dispatch_call_block_and_release + 32 (libdispatch.dylib + 9732) [0x1a8a0c604]
>                                       73  __112-[EXConcreteExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]_block_invoke + 1092 (ExtensionFoundation + 140920) [0x1bb6da678]
>                                         73  -[EXExtensionContextImplementation _willPerformHostCallback:] + 84 (ExtensionFoundation + 73372) [0x1bb6c9e9c]
>                                           73  __112-[EXConcreteExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]_block_invoke.199 + 228 (ExtensionFoundation + 141888) [0x1bb6daa40]
>                                             73  ??? (Userscripts Extension + 20736) [0x100c45100]
>                                               73  ??? (Userscripts Extension + 26896) [0x100c46910]
>                                                 73  ??? (Userscripts Extension + 46292) [0x100c4b4d4]
>                                                   73  ??? (Userscripts Extension + 146412) [0x100c63bec]
>                                                     73  ??? (Userscripts Extension + 142224) [0x100c62b90]
>                                                       73  -[NSRegularExpression(NSMatching) firstMatchInString:options:range:] + 188 (Foundation + 775596) [0x1a9bd25ac]
>                                                         73  -[NSRegularExpression(NSMatching) enumerateMatchesInString:options:range:usingBlock:] + 620 (Foundation + 388468) [0x1a9b73d74]
>                                                           73  icu::RegexMatcher::find(UErrorCode&) + 1664 (libicucore.A.dylib + 1915168) [0x1ab21d920]
>                                                             10  icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 9696 (libicucore.A.dylib + 1927628) [0x1ab2209cc]
>                                                             7   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 248 (libicucore.A.dylib + 1918180) [0x1ab21e4e4]
>                                                             6   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 8532 (libicucore.A.dylib + 1926464) [0x1ab220540]
>                                                             6   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 340 (libicucore.A.dylib + 1918272) [0x1ab21e540]
>                                                             6   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 292 (libicucore.A.dylib + 1918224) [0x1ab21e510]
>                                                             5   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 9516 (libicucore.A.dylib + 1927448) [0x1ab220918]
>                                                             3   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 684 (libicucore.A.dylib + 1918616) [0x1ab21e698]
>                                                             3   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 480 (libicucore.A.dylib + 1918412) [0x1ab21e5cc]
>                                                             2   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 8496 (libicucore.A.dylib + 1926428) [0x1ab22051c]
>                                                             2   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 7488 (libicucore.A.dylib + 1925420) [0x1ab22012c]
>                                                             2   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 5256 (libicucore.A.dylib + 1923188) [0x1ab21f874]
>                                                             2   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 3460 (libicucore.A.dylib + 1921392) [0x1ab21f170]
>                                                             2   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 504 (libicucore.A.dylib + 1918436) [0x1ab21e5e4]
>                                                             2   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 272 (libicucore.A.dylib + 1918204) [0x1ab21e4fc]
>                                                             2   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 236 (libicucore.A.dylib + 1918168) [0x1ab21e4d8]
>                                                             1   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 11072 (libicucore.A.dylib + 1929004) [0x1ab220f2c]
>                                                             1   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 10520 (libicucore.A.dylib + 1928452) [0x1ab220d04]
>                                                             1   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 9544 (libicucore.A.dylib + 1927476) [0x1ab220934]
>                                                             1   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 9460 (libicucore.A.dylib + 1927392) [0x1ab2208e0]
>                                                             1   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 8796 (libicucore.A.dylib + 1926728) [0x1ab220648]
>                                                             1   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 8760 (libicucore.A.dylib + 1926692) [0x1ab220624]
>                                                             1   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 8180 (libicucore.A.dylib + 1926112) [0x1ab2203e0]
>                                                             1   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 4600 (libicucore.A.dylib + 1922532) [0x1ab21f5e4]
>                                                             1   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 4552 (libicucore.A.dylib + 1922484) [0x1ab21f5b4]
>                                                             1   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 4476 (libicucore.A.dylib + 1922408) [0x1ab21f568]
>                                                             1   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 828 (libicucore.A.dylib + 1918760) [0x1ab21e728]
>                                                             1   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 500 (libicucore.A.dylib + 1918432) [0x1ab21e5e0]
>                                                             1   icu::RegexMatcher::MatchAt(long long, signed char, UErrorCode&) + 384 (libicucore.A.dylib + 1918316) [0x1ab21e56c]
> 
>   Binary Images:
>            0x100c40000 -        0x100c77fff  com.userscripts.macos.Userscripts-Extension 4.1.0 (47) <9CB60DBB-6C48-378F-B79B-FEB4D68D79E5>  /Applications/Userscripts.app/Contents/PlugIns/Userscripts Extension.appex/Contents/MacOS/Userscripts Extension
>            0x100dc8000 -        0x100e43fff  dyld (955)                                             <FBB89662-E6F2-3434-B542-F75185AC5E74>  /usr/lib/dyld
>            0x1a88fb000 -        0x1a893cfff  libxpc.dylib (2236.100.61)                             <4C6EB90B-BD32-3CAD-9F25-C9F234775EFB>  /usr/lib/system/libxpc.dylib
>            0x1a8a0a000 -        0x1a8a50fff  libdispatch.dylib (1325.100.36)                        <DC048E3B-E023-3D17-AFE5-4FF3DC625608>  /usr/lib/system/libdispatch.dylib
>            0x1a8c1a000 -        0x1a915ffff  com.apple.CoreFoundation 6.9 (1858.112)                <8E1809FF-F5B1-3D9E-BE15-F2E7B1D8CE51>  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
>            0x1a9b15000 -        0x1a9f05fff  com.apple.Foundation 6.9 (1858.112)                    <886A3487-88A6-30BB-B179-1A92996C67CF>  /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
>            0x1ab04a000 -        0x1ab2fffff  libicucore.A.dylib (70104)                             <BF9FC4BA-0459-3B15-9630-F3B0AA3903DD>  /usr/lib/libicucore.A.dylib
>            0x1b427a000 -        0x1b42b1fff  com.apple.pluginkit.framework 1.0 (1)                  <85C81A87-A22D-383D-9A5E-C26B0D8A445B>  /System/Library/PrivateFrameworks/PlugInKit.framework/Versions/A/PlugInKit
>            0x1bb6b8000 -        0x1bb703fff  com.apple.ExtensionFoundation 34.5 (34.5)              <D3F061C3-5B84-3F32-A1CB-C441B1805179>  /System/Library/PrivateFrameworks/ExtensionFoundation.framework/Versions/A/ExtensionFoundation

**Comment by zexpe** [comment] 2022-05-21 19:07
I hadn't realised macOS generates diagnostic reports for high CPU usage processes. Why has nobody ever written an app to notifier the user whenever such a report is created? Would save my battery on a few occasions - I keep the activity monitor CPU usage in the dock, but don't always spot these runaway processes.

Anyway, looking further through the logs I see reports from 28th April (14:13), 12th May (11:25), 19th May (11:45), 21st May (15:48). That's probably a reasonable representation of when it began, and how often it occurs.

**Comment by quoid** [comment] 2022-05-21 21:10
Thank you very much @zexpe 

It looks like you're on version 4.1.0 (app store version) and not beta, can you confirm for how long you've been using this extension? The reason I ask is that the reports started 28 of April and I am curious if this coincided with a macOS update to (to 12.3 or 12.3.1) or this has been happening since you've been using the extension.

> I hadn't realised macOS generates diagnostic reports for high CPU usage processes. 

I was also unaware of that until this issue. I am not sure how long they persist for as some that I saw and put in the screenshots above have seemingly disappeared :/

**Comment by quoid** [comment] 2022-05-21 21:15
Also would you be willing to send me one of the diagnostic reports? (right click `Reveal in Finder` in `Console.app`). My email is on my profile page. If you're not comfortable sending it, I understand, so no pressure.

**Comment by zexpe** [comment] 2022-05-21 22:33
I've been using the extension since I got this laptop late last year, and 28th April was when I first saw this problem. So presumably sometime after the update to 12.3.1. My reports go back to 30th March, but I doubt the problem occurred before 28th April - I would have noticed it from the CPU usage in the Activity Monitor app dock icon.

BTW, I've turned on a "Folder Action" to monitor new reports being added to the /Library/Logs/DiagnosticReports folder. It seems to work quite well. UserScripts hit 100% CPU again this evening whilst I was using a different app to Safari on my laptop, without any sleep/wake cycles. I'll e-mail the report to you. Haven't updated macOS yet...

**Comment by zexpe** [comment] 2022-06-01 11:56
Just happened again on macOS 12.4 now.

> Date/Time:        2022-06-01 12:50:18.897 +0100
End time:         2022-06-01 12:52:43.200 +0100
OS Version:       macOS 12.4 (Build 21F79)
Architecture:     arm64e
Report Version:   35.1
Incident Identifier: 9B448353-F489-4012-BF5D-9029FD7E4757
Share With Devs:  Yes

> Command:          Userscripts Extension
Path:             /Applications/Userscripts.app/Contents/PlugIns/Userscripts Extension.appex/Contents/MacOS/Userscripts Extension
Identifier:       com.userscripts.macos.Userscripts-Extension
Version:          4.1.0 (47)

> Event:            cpu usage
Action taken:     none
CPU:              144 seconds cpu time over 144 seconds (100% cpu average), exceeding limit of 80% cpu over 180 seconds

**Comment by quoid** [comment] 2022-06-01 14:51
@zexpe 

I haven't yet updated to 12.4, but I am using that folder action you made as well. I haven't yet gotten alerted about Userscripts, but I have for other apps (although their average so far is ~70%).

I was thinking maybe this could be due to hardware limitations, such as older machines, but we have the same model (2021 M1 Pro).

**Comment by zexpe** [comment] 2022-06-10 17:11
For what it's worth, I've not seen a recurrence of this issue since updating to Userscripts 4.2.0. It's been over a week now without this happening.

**Comment by quoid** [comment] 2022-06-10 17:14
@zexpe thanks for the update, I have not seen it since setting up the alerts, but I have been on the beta 4.2.0 before I set that up

I'll close this issue, but if it re-appears, feel free to re-open, thanks again

**Closed by quoid** 2022-06-10 17:14 UTC

**Comment by v7rzlhb3xg** [comment] 2023-05-07 20:29
Same or at least similar issue has started happening again for me for the past couple weeks. macOS Ventura 13.3.1, Safari 16.4, Userscripts 4.4.1. Scripts seem to stop working after an extended period of Safari uptime, requiring me to either restart Safari or manually load the extension through Menubar > Develop > Web Extension Background Content > Userscripts (not loaded). Can't seem to find any error logs since the extension doesn't load in the first place.

**Comment by quoid** [comment] 2023-05-08 01:00
Thanks for the report @v7rzlhb3xg. I am not sure what we can do here without logs 🤔 

I just recently upgraded to 13.3.1, so I will personally see if I become affected by this.

**Comment by v7rzlhb3xg** [comment] 2023-05-12 01:50
@quoid Here's two logs I managed to get when Safari crashed after attempting to manually load the extension through the Web Extension Background Content menu, not sure how useful they are but hope they offer some insight!

[Safari Crash Report 2023-05-11 21.38.58.txt](https://github.com/quoid/userscripts/files/11457976/Safari.Crash.Report.2023-05-11.21.38.58.txt)
[Safari Log Report 2023-05-11 21.38.58.txt](https://github.com/quoid/userscripts/files/11457977/Safari.Log.Report.2023-05-11.21.38.58.txt)

**Comment by quoid** [comment] 2023-05-12 02:06
Thanks for the logs @v7rzlhb3xg. I didn't see anything glaring in there that would indicate an issue, but then again, I am not great at parsing logs from macOS.

Would you mind backing up all of your scripts and taking note of your settings and trashing the extension folders in `~/Library/Containers`? They'd be called `Userscripts` or `com.userscripts.macos` - basically any folder that has the word `userscripts` in it that isn't part of another app.

I am not sure if this would help, but that's something I would try. Again, only if your comfortable doing this and make sure to backup your script files.
