### ISSUE TITLE
Refused to execute a script with when using @inject-into since 3.2.0 version

### ISSUE THREAD

**Issue by mikigal** [quoid/userscripts#139] opened 2021-06-14 22:05 UTC
_System Information:_
> macOS version: 11.4 (20F71)
> Userscripts version: 3.2.0
> Safari version: 14.1.1 (16611.2.7.1.4)

I've got `Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.` error even with `@inject-into` property setted to `auto` and `content`.

Problem does not exist on older version, logs from older version are below

![Zrzut ekranu 2021-06-15 o 00 11 02](https://user-images.githubusercontent.com/10632503/121965981-2cfff280-cd6e-11eb-9807-cdddd3699a35.png)

**Comment by quoid** [comment] 2021-06-14 22:12
@mikigal 

please include the userscript or a simplified version of it

**Comment by mikigal** [comment] 2021-06-14 22:14
@quoid 
Problem exists on every of my scrips, it's one of simplier (version for older Userscripts, without @inject-into)

```javascript
// ==UserScript==
// @name        GitHub Tab Fix
// @description GitHub Tab Fix
// @match       https://github.com/*
// ==/UserScript==

console.log("Executed Userscript!");
let bodies = document.getElementsByTagName("tbody");
if (bodies.length === 0) {
    return;
}

let body = bodies[0];
body.innerHTML = body.innerHTML.replaceAll("\t", "    ")```

**Comment by quoid** [comment] 2021-06-14 22:16
> Problem exists on every of my scrips

Every single script for every single website produces this error? 

Or

Every single script for github domain produces this error?

>  it's one of simplier (version for older Userscripts, without @inject-into)

To be clear, the script you pasted is currently producing an error?

**Comment by mikigal** [comment] 2021-06-14 22:18
I have scripts for YouTube, GitHub, jbzd.com.pl and wykop.pl, they don't work on every site.
Pasted script works with Userscripts 3.1.0, on 3.2.0 it produces error, even when I add @inject-into

**Comment by quoid** [comment] 2021-06-14 22:41
@mikigal

The script you pasted "works" on GitHub. Also the [image you linked](https://user-images.githubusercontent.com/10632503/121965981-2cfff280-cd6e-11eb-9807-cdddd3699a35.png) **also** shows that script injection is occurring.

You can see clearly image the console output of `Executed Userscript!`.  As for the other code in the userscript, that's irrelevant at the moment, because the issue is with script injection and script injection is seemingly working.

If you use this simplified version of what you pasted, visit github.com, and you see the expected console message, injection is working.

```js
// ==UserScript==
// @name        GitHub Tab Fix
// @description GitHub Tab Fix
// @match       https://github.com/*
// ==/UserScript==

console.log("Executed Userscript!");
```


> it produces error

The error will always show *when a website has a strict CSP*, but that does not mean that script injection has failed. When a CSP error occurs, the extension automatically attempts a fallback method of script injection (you can tell this by the `console.warning` message which is present in your screenshot image).

In the case of Github `->` has a strict CSP, error gets thrown, fallback method is attempted, script is injected.

> I have scripts for YouTube, GitHub, jbzd.com.pl and wykop.pl, they don't work on every site.

Ensure that you are using proper `@match` values. In 3.2, matching was improved but it also could make old `@match` values no longer function as expected.

I am able to inject scripts into Youtube, GitHub, jbzd.com.pl and wykop.pl with no issues.

Check out this article for constructing match patterns: https://developer.chrome.com/docs/extensions/mv3/match_patterns/

**Comment by mikigal** [comment] 2021-06-14 22:44
Logs which I pasted are from 3.1.0, I wanted to show message about fallback. 
On 3.2.0 I've got only `Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.` and nothing more. My console.log is not executed.

Maybe my `@match` get broken in 3.2, I will verify it

**Comment by quoid** [comment] 2021-06-14 22:52
@mikigal 

> Logs which I pasted are from 3.1.0, I wanted to show message about fallback.
> On 3.2.0 I've got only Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. and nothing more. My console.log is not executed.

This is why it is important to post the exact userscript that is causing the issue. Above you posted a userscript, but made a comment about how it was "version for older Userscripts" - this is not helpful because I can not see the code that is causing the issue.

All I can tell you is that injection is working here, so I would guess it would be a metadata issue that can be very quickly solved. However, if I can see the userscripts causing the issue, I can help much.

I tested all the domains you listed and had no issues with injection.

<img width="1275" alt="Screen Shot 2021-06-14 at 6 46 09 PM" src="https://user-images.githubusercontent.com/7660254/121969096-97e70480-cd41-11eb-86df-2db7be50da89.png">

**Comment by quoid** [comment] 2021-06-14 22:58
I tested all the domains you listed and had no issues with injection. It must be a metadata syntax issue. 

<img width="1275" alt="Screen Shot 2021-06-14 at 6 46 09 PM" src="https://user-images.githubusercontent.com/7660254/121969096-97e70480-cd41-11eb-86df-2db7be50da89.png">

If you provide the userscript that is causing issue and the domain you are visiting I can probably tell you very quickly what the issue is.

**Comment by mikigal** [comment] 2021-06-14 22:59
I reinstalled 3.2.0 and it started working - I haven't idea what happend, very sorry for problems.
Currently it only throws TypeError, logs below.

Code:
```javascript
// ==UserScript==
// @name        GitHub Tab Fix
// @description GitHub Tab Fix
// @match       https://github.com/*
// ==/UserScript==

console.log("Executed Userscript!");
```
![Zrzut ekranu 2021-06-15 o 00 58 10](https://user-images.githubusercontent.com/10632503/121969581-ea8de400-cd74-11eb-9fba-ab15bad013ec.png)

**Comment by quoid** [comment] 2021-06-14 23:19
> Currently it only throws TypeError, logs below.

is this happening every page load?

**Comment by mikigal** [comment] 2021-06-14 23:22
It happens about 4-5 times on 10 page reloads

**Comment by quoid** [comment] 2021-06-14 23:25
@mikigal 

If I had to guess this is happening because the CSP error is getting thrown before the content scripts gets the userscript `data`. 

are you using any other userscript managers?

**Comment by mikigal** [comment] 2021-06-14 23:26
No, I have only AdGuard, Dark Reader and UserScripts extensions

**Comment by quoid** [comment] 2021-06-14 23:32
The issue, I reckon, is that something *else* is triggering the CSP error. When that error happens, the event listener in the Userscripts content script is running the fallback function, but this is happening before the data is received.

I reckon one of the other extensions have extension scripts, you can check this by looking in the developer tools. You will see in the screenshot below, I have 1password extension with a script as well:

<img width="576" alt="Screen Shot 2021-06-14 at 7 27 57 PM" src="https://user-images.githubusercontent.com/7660254/121971562-fc589280-cd46-11eb-84a8-cd036e27ed36.png">

If you don't mind checking that I would appreciate it.

Although not the reason of this issue, it exposed another potential bug!

**Comment by mikigal** [comment] 2021-06-14 23:35
So my issue wasn't as useless as I thought 😆

![Zrzut ekranu 2021-06-15 o 01 34 08](https://user-images.githubusercontent.com/10632503/121971766-cb458580-cd79-11eb-9ff7-b68934753b9d.png)

**Comment by quoid** [comment] 2021-06-14 23:38
@mikigal it was not!

Thank you for the image, I believe the issue is happening because of what I mentioned above. I will try to patch it tonight and hopefully it will be in app store very soon.

I opened a new issue for the bug and you can track it there if you want: #140 

I am going to close this, thank you!

**Closed by quoid** 2021-06-14 23:38 UTC
