### ISSUE TITLE
No matched userscripts, but found in directory

### ISSUE THREAD

**Issue by anon238** [quoid/userscripts#210] opened 2022-01-16 14:08 UTC
I downloaded [this userscript](https://raw.githubusercontent.com/Laurvin/NPO-Start-Downloader/master/NPO_Start_Downloader.user.js) and placed it in a directory. The extension can find it as seen in this image, but in the main screen it says there are no matched userscripts:

 ![84AA0760-3E19-4214-921E-D803F0DFA990](https://user-images.githubusercontent.com/76251639/149663249-70aef552-ff9a-4b9e-8076-ad9fc4523164.jpeg)

_System Information:_
> macOS or iOS version: iOS 15.2.1
> Userscripts version: v0.1 (13)
> Safari version: N/A
> Is this issue related to script injection?: N/A
> Did the test script (pasted above) successfully run on your machine?: I don’t have a machine to test, iPhone only.
> I gave permission to run the extension on Safari.

**Comment by quoid** [comment] 2022-01-16 14:11
>  The extension can find it as seen in this image, but in the main screen it says there are no matched userscripts:

When it says "no matched userscripts", what url are you on?

**Comment by anon238** [comment] 2022-01-16 14:23
> > The extension can find it as seen in this image, but in the main screen it says there are no matched userscripts:
> 
> When it says "no matched userscripts", what page url are you on?

Thanks for the quick reply. I have tested it on these websites:

`1: https://eenvandaag.avrotros.nl/item/miljoenen-gereserveerd-voor-schikkingen-met-narcolepsiepatienten`  

`2: https://start-player.npo.nl/embed/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRvcGxheSI6IjAiLCJhc3NldFVybCI6IiIsImNvbG9yIjoiI2VmNmMwMCIsInN0eWxlc2hlZXQiOiJodHRwczpcL1wvcmVzb3VyY2VzLmFzc2V0cy5hdnJvdHJvcy5ubFwvYXZyb3Ryb3MtcmVzb3VyY2VzXC9zdHlsZXNcL25wby1wbGF5ZXIubWluLmNzcz92PWF0LTA2NjQ4YzE2ZDQiLCJoYXNBZENvbnNlbnQiOiIiLCJzaGFyZSI6IjAiLCJub0FkcyI6MCwicmVjb21tZW5kYXRpb25zIjowLCJlbmRzY3JlZW4iOiIwIiwibW9yZUJ1dHRvbiI6IjAiLCJzdGVyU2l0ZUlkIjoiZWVudmFuZGFhZyIsInN0ZXJJZGVudGlmaWVyIjoiZWVudmFuZGFhZy1kZXNrdG9wIiwic21hcnR0YWciOnsic2l0ZUlkIjoiMTAifSwic2hhcmVVcmwiOiJodHRwczpcL1wvZWVudmFuZGFhZy5hdnJvdHJvcy5ubFwvaXRlbVwvbWlsam9lbmVuLWdlcmVzZXJ2ZWVyZC12b29yLXNjaGlra2luZ2VuLW1ldC1uYXJjb2xlcHNpZXBhdGllbnRlblwvIiwic3RlclJlZmVycmFsVXJsIjoiaHR0cHM6XC9cL2VlbnZhbmRhYWcuYXZyb3Ryb3MubmxcL2l0ZW1cL21pbGpvZW5lbi1nZXJlc2VydmVlcmQtdm9vci1zY2hpa2tpbmdlbi1tZXQtbmFyY29sZXBzaWVwYXRpZW50ZW5cLyIsIm92ZXJsYXkiOiJodHRwczpcL1wvZWVudmFuZGFhZy5hc3NldHMuYXZyb3Ryb3MubmxcL19wcm9jZXNzZWRfXC80XC8yXC9jc21fc2VubmFfbmFyY29sZXBzaWVfdmVyZ29lZGluZ19lODM3MDc2NjFhLmpwZyIsImlhdCI6MTY0MjMzOTgzNSwibmJmIjoxNjQyMzM5ODM1LCJleHAiOjE2NDIzNjg2MzUsImNvbnN1bWVySWQiOiJjYjA1ZWQ3Yy0wNDFiLTQ3MzAtYWUxNy05ZGY5Y2I0OWZkYjMiLCJtZWRpYUlkIjoiUE9NU19BVF8xMzA5MzY2NiIsImlzUGxheWxpc3QiOmZhbHNlLCJyZWZlcnJlclVybCI6bnVsbCwic2tpcENhdGFsb2ciOjAsImlzcyI6ImV5SnBkaUk2SW1odU9XZEVRM2sxVlV4UE9GWXlNWGxKTkdOa1dtYzlQU0lzSW5aaGJIVmxJam9pU2tWR09XeHJSM1Z3UkZKeVZUWTJhR2h2VUdoVGVUbEZhRFZzYkZ3dlJHVnJZbmw1VjNWMFYyMUZiVW96TWpKSVpGUlZkbEpWU3podGNrd3dXV1pCTW1RaUxDSnRZV01pT2lJeU1tUmpNR1F3WW1NMVl6TXlZalUyTkRka01ESTFZakk1WW1Sa01qRmtaVGcxTTJVek5EWTFZamhrWkRnM1pHSm1aVFZpT0RZMk1XUmxaalZpTkRkbEluMD0ifQ.MQM2KdooGoXUjJjbmOfUYvbTDypt34y-F8D8IuFAXyc`

**Comment by anon238** [comment] 2022-01-16 14:29
> > The extension can find it as seen in this image, but in the main screen it says there are no matched userscripts:
> 
> When it says "no matched userscripts", what page url are you on?

I also tested it with this Dark Wikipedia userscript, but unfortunately without success.

[Dark Wikipedia - Userscript for iOS & macOS Safari · GitHub](https://gist.github.com/kfatehi/6253953ded8c24b895013477da1e2675)

**Comment by quoid** [comment] 2022-01-16 14:45
@anon238 

In the first comment you mentioned that `No matched userscripts` is displayed. 

In the above comment you pasted two urls, one of which is a `404`. The first one starts with `https://eenvandaag.avrotros.nl/` and the second starts with `https://start-player.npo.nl`. Neither of those urls patterns are present in the (userscript's metadata)(https://raw.githubusercontent.com/Laurvin/NPO-Start-Downloader/master/NPO_Start_Downloader.user.js) that you linked. The expected behavior is that it does *not* show there, because it doesn't match those urls.

To be clear, the popup should only show a userscript when the userscript matches to the url you are currently on. If you see the userscript in "All userscripts" but not in the main window for the page url you are on, it *most likely* an issue with the userscript itself. 

In your case, the metadata (`@include` or `@match`) in the userscript would have to be updated for those url patterns you listed.

As a side note, *not related* to the "No matching userscripts" message, I'd also point out, [that userscript](https://github.com/Laurvin/NPO-Start-Downloader/blob/master/NPO_Start_Downloader.user.js) has not been updated in 4 years. If you do end up on a url that matches, I am not sure how much functionality I'd expect.

> I also tested it with this Dark Wikipedia userscript, but unfortunately without success.

I actually use that userscript myself, it works on my iphone as expected. When you says "without success" what do you mean exactly?

<img src="https://user-images.githubusercontent.com/7660254/149664547-6e348d8a-d475-4f81-855c-f9f29f045189.jpeg" width="50%">

**Comment by anon238** [comment] 2022-01-16 15:07
Wikipedia is fixed I had to gave Safari permissions to all websites otherwise it wouldn’t work. For the other script thanks for the explanation, can I add wildcards in userscripts?

**Comment by quoid** [comment] 2022-01-16 15:11
Great!

> For the other script thanks for the explanation, can I add wildcards in userscripts?

Yes, but the usage depends on which key you use, `match` or `include`. The metadata section links out to some good tutorials: https://github.com/quoid/userscripts#metadata

Again, even with the proper `match` or `include` values, I don't think that userscript will work due to it not being updated in quite some time. However, I could be wrong.

Now that the we've pinpointed the source of your problem and it's not something wrong with the extension or app, I am going to close this issue.

Thanks

**Closed by quoid** 2022-01-16 15:11 UTC
