### ISSUE TITLE
finance.yahoo must reload

### ISSUE THREAD

**Issue by TraderStf** [quoid/userscripts#117] opened 2021-04-24 16:24 UTC
_System Information:_
> macOS version: 11.2.3
> Userscripts version: 31
> Safari version: 14.03

Thanks for such a nice tool!

I made a script for finance.yahoo.com
.gemini-ad {display:none !important}

but must reload the page to get rid of the ads.

Sorry, I'm not used to this kind of "delete"
I have tried a ~getelementby... remove() but did not work.

thanks

**Comment by quoid** [comment] 2021-04-24 16:45
@TraderStf 

Can you please paste the entire userscripts you have tried? 

Thanks

**Comment by TraderStf** [comment] 2021-04-24 16:57
My script was without a doubt bad. Something like, I delete it
var yads = document.getElementsByClassName('gemini-ad');
yads.remove();

then another try with a ForEach

My goal was to avoid loading the ads, as the display:none just hide it.
But it's perhaps useless as the script acts after the download.

Don't worry, thank you so much for this great tool!

**Comment by quoid** [comment] 2021-04-24 20:29
@TraderStf 

I made a small test `css` userscript:

```css
/* ==UserStyle==
@name        Test Yahoo
@description This is your new file, start writing code
@match       *://finance.yahoo.com/*
==/UserStyle== */

.gemini-ad {
    display: none;
}
```

It seems to function as intended on [finance.yahoo.com](finance.yahoo.com), without the need to reload.

If you have time, could you test it on your machine and let me know if it works? Click `+`, then `New CSS` and then paste the above code. It's best to test with all other userscripts disabled as they could be the cause of the issues.

**Comment by TraderStf** [comment] 2021-04-25 06:36
It seems ok. Here is the code I was using. Perhaps the download was blocked and I saw the ads before they get hidden.
I made several tests: relaunch, close, clean cache, disable all extensions/LS/Kasper...
LittleSnitch, Kaspersky and my DNS resolver: nextdns.io
are already blocking a lot of things which sometimes blocks/slows the display of all the page.
Thank you very much.

".native-ad-item" is a better choice, it works on all pages, not just the main one.

```
/* ==UserStyle==
@name        YahooFinance
@description Block Ads
@match       https://*.yahoo.com*
==/UserStyle== */
.gemini-ad {display:none !important}

```

**Comment by TraderStf** [comment] 2021-04-25 07:05
I got a problem with the editor, create a new one, exactly the same as above, just for another site and class.
No matter what I do, delete key, remove space, comments, move the caret from top to bottom to find a hidden character... it was always reporting ~syntax errors.
Finally I saved it (attached), trash it and redo it manually without paste from textedit.

[LeVif.js.txt](https://github.com/quoid/userscripts/files/6371414/LeVif.js.txt)

**Comment by quoid** [comment] 2021-04-25 13:36
@TraderStf 

> It seems ok. Here is the code I was using.

Yeah, the userscript you pasted seems to work as expected.

> I got a problem with the editor, create a new one, exactly the same as above, just for another site and class.
No matter what I do, delete key, remove space, comments, move the caret from top to bottom to find a hidden character... it was always reporting ~syntax errors.
Finally I saved it (attached), trash it and redo it manually without paste from textedit.

Is what you've attached the code that was presenting the issue or is it the code you used once you resolved the issue? The userscript you linked seems to function as expected on `https://www.levif.be/`

If possible, can you post the code that is presenting the issue and the include the specific `url` you are visiting where the issue takes place. I am hoping to be able to reproduce the issue so I can properly debug.

Unfortunately I've not been able to reproduce either of the issues you've mentioned yet 😕

**Comment by TraderStf** [comment] 2021-04-25 14:34
Oh sorry for the confusion, the site where the editor bug occurred:
https://www.levif.be/
The code attached is the one I had pasted from Textedit, almost immediately there was a ~brown dot, highlighting several errors. There was no error, it's the same code. No matter what I have tried, editing it, spacesss, several lines, always error. Colored syntax was also missing, all ~white.
Finally I deleted that entry, create a new one and paste from the first code mentioned at the top of this thread.
Everything was ok immediately.
Probably Textedit add some gremlins... That's why I save it before delete it so you can inspect it.
Here is the hexdump from the saved/attached file.

`
0000: 2F 2A 20 3D 3D 55 73 65 72 53 74 79 6C 65 3D 3D 	/* ==UserStyle==

0010: 0A 40 6E 61 6D 65 20 20 20 20 20 20 20 20 4C 65 	.@name        Le

0020: 56 69 66 0A 40 64 65 73 63 72 69 70 74 69 6F 6E 	Vif.@description

0030: 20 42 6C 6F 63 6B 20 41 64 73 0A 40 6D 61 74 63 	 Block Ads.@matc

0040: 68 20 20 20 20 20 20 20 68 74 74 70 73 3A 2F 2F 	h       https://

0050: 2A 2E 6C 65 76 69 66 2E 62 65 2F 2A 0A 3D 3D 2F 	*.levif.be/*.==/

0060: 55 73 65 72 53 74 79 6C 65 3D 3D 20 2A 2F 0A 2E 	UserStyle== */..

0070: 72 6D 67 53 68 61 72 65 73 7B 64 69 73 70 6C 61 	rmgShares{displa

0080: 79 3A 6E 6F 6E 65 3B 7D                         	y:none;}
`

**Comment by quoid** [comment] 2021-04-25 14:40
@TraderStf 

Is this what you did?

- create script in TextEdit
- paste script into extension editor
- error occurred

??

> there was a ~brown dot, highlighting several errors

What was highlighting errors?

> Probably Textedit add some gremlins...

That what I would imagine, but I have not experience that personally. I never use TextEdit for script creation specifically because rich text editors can cause problems. [Sublime Text](https://www.sublimetext.com) is a good alternative to TextEdit.

**Comment by TraderStf** [comment] 2021-04-25 14:43
I made some quick tests, paste a valid code (your code in your 2nd answer) from a TextEdit .txt (not rtf/style) block the syntax coloring. Line 6 remains white, no matter what you do. No brown error dot.

**Comment by TraderStf** [comment] 2021-04-25 14:44
Yes it is the "highlighting errors?"

**Comment by quoid** [comment] 2021-04-25 14:45
Where is the brown dot error showing? In TextEdit or the extension editor?

If it is showing the extension editor, is the brown dot, the thing you seen in my image?

Sorry, I am still slightly confused

**Comment by TraderStf** [comment] 2021-04-25 14:45
I use BBEdit, don't worry it was FYI. TextEdit has some bugs sometimes, depends of the contents you paste in it...
Thank you :-)

**Comment by quoid** [comment] 2021-04-25 14:51
@TraderStf when you get a chance, please let me know what the "brown dot" is. 

Is it something from the extension editor (like the [image](https://user-images.githubusercontent.com/7660254/115997869-c4d53180-a5b2-11eb-9b2b-52a5b07ecdb0.png) I pasted above) or from something else.

**Comment by TraderStf** [comment] 2021-04-25 14:59
hum... it is not only from TextEdit. I copy your ALL the code, from your second answers here above from github page.
Paste it in a brand new entry: Select all default code, paste.
No syntax color, line 7,8,9 are white, no orange dot.

If I type 1 or more characters in _line_ 6, line 7 has "gemini" ONLY in red. No error dot.

`6 a`
`7 .gemini-ad {`

<hr>

The orange and red dots appeared in the code which contains line/class .rmgShares
If I move the mouse cursor over it and I had orange and red error lines, most were duplicated, I think 2 or 3 times in the popup menu.

**Comment by quoid** [comment] 2021-04-25 15:01
@TraderStf can you please take a screenshot of the editor so I can see? 

I really want to see what is happening

**Comment by TraderStf** [comment] 2021-04-25 15:04
The brown dot was in Extension Editor, yes it what I called the round dot.
Forget about it.
If it occurs again, I would make more serious tests.
Thank you and have a nice Sunday!

**Comment by quoid** [comment] 2021-04-25 15:12
Thank you for taking the time to assist with this.

If you were seeing the dot in the edit, I assume you have `Javascript Linter` option toggled `on` in the settings. The dot looked orange to me, that was causing some confusion.

However, I believe the issue is that you were attempting to paste `CSS` code into a `Javascript` item. You should *never* see the Javascript linter in the `CSS` item type. If the syntax highlighting was not showing up, that further suggests that the code in the editor was of the wrong type.

All `CSS` code should be contained in `CSS` type items:

<img width="611" alt="Screen Shot 2021-04-25 at 11 08 15 AM" src="https://user-images.githubusercontent.com/7660254/115998714-95282880-a5b6-11eb-82f2-f5ea9405873e.png">

Without seeing a screenshot of the actual issue I can not be 100% sure this is the cause. If you change your mind and decide to share a screenshot, I would appreciate it. If not, thank for the time you've already spent on this.

**Comment by TraderStf** [comment] 2021-04-25 15:18
Doooo I am so sorry, that's what I did... I was trying a JS and when I want to make tests for this thread, I paste it in the current entry I was working!
🧠 upgrade required... SORRY!!! 🙈🦥
Thanks to you.
BTW it's gorgeous too!

**Comment by TraderStf** [comment] 2021-04-25 15:38
What's going on with Apple crapy Appstore, already 46 reviews but can't see summary, only on the web page...
Anyway, I added a great review and comment about your pro support.
Sorry again :-/

**Comment by quoid** [comment] 2021-04-25 16:04
@TraderStf 

> Sorry again :-/

Absolutely no need to apologize! I am glad I was able to help!

I very much appreciate the review!!

I am going to close the issue now since this is resolved 👍

**Closed by quoid** 2021-04-25 16:04 UTC
