### ISSUE TITLE
Userscript injection not working at all?

### ISSUE THREAD

**Issue by Rediwed** [quoid/userscripts#239] opened 2022-04-12 09:02 UTC
First of all, sorry for not filling out the form. I am not able to fill it in because it is too specific for my issue.

For some reason, I can’t get any userscript to work at all. I’ve followed all the necessary steps from the README.md. The script extension itself is visible and the injector is activated. Safari has also been set to allow the extension on every page. However yet, none of the userscripts that I have installed have any effect on the webpage. I’ve tried:

- Google Hit Hider by Domain
- View Image for Google Images
- Sci-hub button
- Unedit and Undelete for Reddit
- Return YouTube Dislike

What did I miss? I wanted to check the Error log, but I can’t find any instructions on where to find the error log.

_System Information:_
> macOS or iOS version: 12.3.1
> Userscripts version: 4.1.0 (47)
> Safari version: 15.4
> Is this issue related to script injection? Yes
> Did the test script (pasted above) successfully run on your machine? No

**Comment by quoid** [comment] 2022-04-13 02:33
@Rediwed 

Sorry to hear it's not working for you. I'll need some more details in order to help.

> Did the test script (pasted above) successfully run on your machine? No

To double check, you installed the test script, then visited a website that **wasn't** a `google.com` domains (ex. https://example.com) and did not see the the console message appear in dev tools?

If running the test script isn't clear, please let me know and I can give you more detailed instructions. Determining if this is an issue with the injection as a whole or the userscripts you are attempting to use is key to solving the issue.

Personally I am using Return YouTube Dislike, from [here](https://raw.githubusercontent.com/Anarios/return-youtube-dislike/main/Extensions/UserScript/Return%20Youtube%20Dislike.user.js) and it is working as intended on my machine.

> I wanted to check the Error log, but I can’t find any instructions on where to find the error log.

There are 2 places you could see errors. The first to check is Safari's [dev tools](https://support.apple.com/guide/safari/use-the-developer-tools-in-the-develop-menu-sfri20948/mac) console. Here's a [walkthrough from Apple](https://developer.apple.com/videos/play/tech-talks/401/).

The second place to check is `console.app`. [This comment](https://github.com/quoid/userscripts/issues/201#issuecomment-1009499586) has some details on how to check that.

The first thing I want to validate is that you know how to run the test script and it was not working.

**Comment by Rediwed** [comment] 2022-04-14 07:03
Hi @quoid, thank you for the response. I just installed the testscript and checked the console. It didn’t work at first, it appears but rebooting fixed that! Now it appears that the YouTube Dislike script works again as well. However, I’m not able to make the other scripts work:

Here’s for example Google Hit Hider. It’s being injected, but it doesn’t work:
https://cln.sh/D87EUvDwScOAKRm6IW70

Same for Sci-hub button injector:
https://cln.sh/qdrsRS1gxjkrxke9dH0t

**Comment by quoid** [comment] 2022-04-14 22:06
@Rediwed 

> I just installed the testscript and checked the dev tools console. It didn’t work at first, it appears but rebooting fixed that!

Glad to hear it is working now. I am not sure how you were originally going about installation, but if you add a script outside of using the editor (example: you drag a file to your save location), the popup must be opened at least once before that script will inject. In short, if you are using an external editor, the popup needs to be opened after new files are created or edits occur.


> However, I’m not able to make the other scripts work

Google Hit Hider is using currently unsupported APIs. Those APIs are [set to be added in v4.3](https://github.com/quoid/userscripts/milestone/9).


I tried to find "Sci-hub button injector", is [this the userscript](https://raw.githubusercontent.com/justjosias/sci-hub-injector/main/sci-hub-inject.user.js)? can you provide me with a link to a website where it **should** be working and **what it is supposed to do**?

I loaded the userscript and am noticing errors when visiting pages where it is supposed to work (see image below). If you answer what is above it would be easier to tell what the problem is. However, it seems to me like this is a problem with the actual script code and not this extension/app. I'd be glad to verify that for you.

<img width="1409" alt="Screen Shot 2022-04-14 at 6 04 56 PM" src="https://user-images.githubusercontent.com/7660254/163483946-32cf7da7-a486-4f7a-9314-2c478bab74e0.png">

**Comment by Rediwed** [comment] 2022-04-23 07:33
Hi there, sorry about the late reply. I had some time with the family over easter, and forgot afterwards.

>Glad to hear it is working now. I am not sure how you were originally going about installation, but if you add a script outside of using the editor (example: you drag a file to your save location), the popup must be opened at least once before that script will inject. In short, if you are using an external editor, the popup needs to be opened after new files are created or edits occur.

This might be the case as well, I wasn’t aware of that. 

>Google Hit Hider is using currently unsupported APIs. Those APIs are [set to be added in v4.3](https://github.com/quoid/userscripts/milestone/9).

Sounds good, I will wait for that!

>I tried to find "Sci-hub button injector", is [this the userscript](https://raw.githubusercontent.com/justjosias/sci-hub-injector/main/sci-hub-inject.user.js)? can you provide me with a link to a website where it should be working and what it is supposed to do?

The Sci-Hub button I’m referring to is [this one](https://greasyfork.org/en/scripts/370246-sci-hub-button/code). I believe the one you referred might be the same, but this one is active on more websites. It’s a tool that finds links to scientific articles, grabs their DOI-ID and looks them up in Sci-Hub. Then, a button to go to Sci-hub is placed after the link.

I’ve used this extension with no problems through AdGuard’s Userscript support. So it might have to do with the way Userscripts handles APIs?

**Comment by quoid** [comment] 2022-04-24 02:50
@Rediwed 

> The Sci-Hub button I’m referring to is [this one](https://greasyfork.org/en/scripts/370246-sci-hub-button/code).

From looking at that userscript, it seems like it should be working. It isn't using any unsupported APIs from what I can see.

> I’ve used this extension with no problems through AdGuard’s Userscript support. So it might have to do with the way Userscripts handles APIs?

When you say *"used this extension"*, do you mean *"used the userscript"*?

If you can give me a link to a page where you expect to see the button, perhaps one where it is working with AdGuard, and a screenshot for what I should be seeing I could look into why this isn't working. I am curious to see what is going on.

**Comment by elyscape** [comment] 2022-04-28 01:14
While Google Hit Hider does use the currently-unsupported `GM.getResourceUrl` API, it's not actually critical to its functionality. What's preventing it from working is the fact that, currently, `GM.getValue()` doesn't correctly handle false values for `defaultValue`. I have submitted a fix for this as #241.

**Comment by elyscape** [comment] 2022-04-28 01:22
To elaborate somewhat, [Google Hit Hider][ghh] has a few places where it calls `GM.getValue()` with the empty string. For example, see line 175:
```javascript
GM.getValue("hiderStyles", "").then(function(value){custSty = value; if (custSty.length > 0) injectCustom();});
```
The problem is in the implementation of `GM.getValue()`:
https://github.com/quoid/userscripts/blob/16a23bd5ea94f9bacbc9a09a21b3ddb779c41d65/extension/Userscripts%20Extension/Resources/background.js#L91-L103
If there is no stored value for `hiderStyles`, the first codepath will be followed. Since the empty string is falsey, execution will fall into line 98, and `undefined` will be returned. The script, expecting to have received some kind of string, then attempts to dereference the `length` attribute, which is invalid.

[ghh]: https://greasyfork.org/en/scripts/1682-google-hit-hider-by-domain-search-filter-block-sites

**Comment by quoid** [comment] 2022-04-28 01:39
Thank you @elyscape !

**Comment by quoid** [comment] 2022-06-02 21:17
closing this issue due to inactivity

**Closed by quoid** 2022-06-02 21:17 UTC
