### ISSUE TITLE
Scripted loading twice after name change

### ISSUE THREAD

**Issue by MisterMediocre** [quoid/userscripts#62] opened 2020-07-29 22:46 UTC
_System Information:_
> macOS version: 10.15.6
> Userscripts version: 2.0.1
> Safari version: 13.1.2 (15609.3.5.1.3)

I changed name of script from hwm_lwm_Leader_Sets to HWM_LWM_Leader_Sets.
Since that change, this script is being loaded twice. And this problem has persisted after repeated quiting/reopening of Safari.

Console log:
[Log] Injecting HWM_LWM_Leader_Sets.js (script.js, line 46)
[Log] Injecting hwm_lwm_leader_sets.js (script.js, line 46)

There is only one file in the scripts folder, which is hwm_lwm_leader_sets.js, but has Name field as HWM_LWM_Leader_Sets
[file has original name, but new content]

In fact, even after disabling the script, it loads once.
[Log] Injecting HWM_LWM_Leader_Sets.js (script.js, line 46)

This is the one that's not even in the scripts folder. It has the updated name. 
My guess is that this file's been created, but not updated in scripts folder and is now living it's independent life.

**Comment by quoid** [comment] 2020-07-30 00:40
@MisterMediocre Thank you very much for this bug report. I was able to reproduce this issue locally.

I believe issue is with how the extension is [validating scripts](https://github.com/quoid/userscripts/blob/c9fcd7ba4aef270601167da9c165f5c1b98080c1/extension/Userscripts%20Extension/Functions.swift#L576) before saving. It's not accounting for name changes where the characters stay the same and just capitalization changes. It treats those names as the same name, when in reality they *are not*. The manifest which tells the browser which scripts to inject adds a new entry for the the new name with different capitalization, but the app doesn't delete the old because it thinks they are same (because they are compared `.lowercased()`).

There really is only one script after you changed the name, it is just being injected twice.

I will address this in the future update, but the time being a quick way to resolve this is:

- click on the offending script
- change the name by adding any new character, for example `WM_LWM_Leader_SetsX`
- save
- change the name back to what you want it to be, for example `WM_LWM_Leader_Sets`

**Comment by quoid** [comment] 2020-07-30 00:45
This issue also exposes something of note:

When a script is injected into a webpage, it is not using the filename in the console message. Rather it uses the `@name` field. With this extension filename and `@names` can differ. Be default userscripts created in the included editor will have matched `@name` fields and filenames. Exceptions occur when:

- a user manually changes the filename of a userscript in the save location
- a user includes a userscript (by drag/drop) that has a filename and `@name` that differ

Perhaps this can be used to implement a `@filename` field, however I am struggling to find value for that metafield.

I am not sure what to do with the above information, but I wanted to note it down for later rumination.

**Comment by MisterMediocre** [comment] 2020-07-30 01:16
Thanks for the prompt response.

**Comment by quoid** [comment] 2020-09-08 19:29
resolved in [2.1.0](https://github.com/quoid/userscripts/releases/tag/v2.1.0)

**Closed by quoid** 2020-09-08 19:29 UTC
Labels: bug
