### ISSUE TITLE
Sync userscripts from Nextcloud webdav

### ISSUE THREAD

**Issue by ifuchs** [quoid/userscripts#255] opened 2022-05-11 21:18 UTC
I would like to be able to sync userscripts across all of my platforms (FF/MacOS,Chrome/MacOS,Safari/MacOS, Safari/iOS). What is the best way to do this? I thought I would use Nextcloud to store the backups and Firefox/MacOS seems able to do this with WebDav but not iOS (or if there is a way, I haven't found it as Nextcloud is grayed out when I open the Userscripts app on iOS).

**Comment by quoid** [comment] 2022-05-11 22:58
@ifuchs I believe this might be a duplicate of https://github.com/quoid/userscripts/issues/234 - if so, can we focus all conversation in that thread?

I plan on looking into this, but it will be some time unless someone makes a PR that can address it.

**Comment by ifuchs** [comment] 2022-05-11 23:38
That’s fine. Before you close this issue, can you tell me what the
recommended way of syncing across macOS and iOS is? I did not see a way of
having firefox store scripts on iCloud but perhaps I’m missing it.

**Comment by quoid** [comment] 2022-05-12 02:28
@ifuchs 

> Before you close this issue, can you tell me what the recommended way of syncing across macOS and iOS is?

The recommended way of syncing between macOS and iOS is to set the userscript location for both platforms to the same folder in your iCloud drive. And to be using Safari running this extension on both platforms.

> I did not see a way of having firefox store scripts on iCloud but perhaps I’m missing it.

This extension won't be aware of any of your firefox scripts because it is a Safari only extension.

I do not believe other userscript managers save to the filesystem like this extension does so I reckon that there are really only two ways to sync scripts across *different* extensions (like ViolentMonkey):

1) Those other managers start allowing userscripts that are saved by the user to be synced to a user selected file system location.

2) This manager gains support for other 3rd party storage (like Nextcloud, Google Drive, etc...). If this were to happen, I believe that other userscript managers (like ViolentMonkey) allow syncing to those services and if that were enabled, the user could select a folder from one of those services as their userscript location, and syncing would occur.

I hope that all makes sense.

**Comment by quoid** [comment] 2022-05-21 14:22
closing this thread in favor of the other, feel free to comment in the other thread or open a new issue if something else comes up - thanks

**Closed by quoid** 2022-05-21 14:22 UTC
